package calculator_module;


/**
* calculator_module/Calculator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Sunday, April 21, 2024 9:22:13 AM IST
*/

public interface Calculator extends CalculatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calculator
