package calculator_module;


/**
* calculator_module/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Sunday, April 21, 2024 9:22:13 AM IST
*/

public interface CalculatorOperations 
{
  int add (int a, int b);
  int subtract (int a, int b);
  int multiply (int a, int b);
  int divide (int a, int b);
  void shutdown ();
} // interface CalculatorOperations
