package calculator_module;

/**
* calculator_module/CalculatorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* Sunday, April 21, 2024 9:22:13 AM IST
*/

public final class CalculatorHolder implements org.omg.CORBA.portable.Streamable
{
  public calculator_module.Calculator value = null;

  public CalculatorHolder ()
  {
  }

  public CalculatorHolder (calculator_module.Calculator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = calculator_module.CalculatorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    calculator_module.CalculatorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return calculator_module.CalculatorHelper.type ();
  }

}
